name: API Test

on: [push, pull_request]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run API Test
        run: |
          export EI_API_KEY="${{ secrets.EI_API_KEY }}"
          export EI_PROJECT_ID="${{ secrets.EI_PROJECT_ID }}"
          cd upload_test
          bash api_test.sh
          bash api_edge_test.sh
